### ISSUE TITLE
Adding support for live stream URL in server.js

### ISSUE THREAD

**Issue by mhdzumair** [Stremio/server-docker#34]
As I tested with live stream URL with latest image, The container raises an error  

```
Error: Live media is not supported
    at Object.get (/stremio/server.js:73176:67)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports.playlist (/stremio/server.js:73255:44)
    at async /stremio/server.js:71254:28
```

also tried to check the server.js with https://dl.strem.io/server/v4.20.8/desktop/server.js

 This will be a valuable addition to users of stremio. As of now, the live stream capability is missing in some clients like Windows Client, Latest Android TV client v1.6.9 and Web Client. However, the live streams are working on Linux, Mac, and Android clients. So i have decided to give a shot via stremio server in Web Client and turns out not supporting error.

**Comment by jaruba** [comment]
but this error is from the transcoding engine, this engine is only used for Stremoo Web, so why would you think this impacts Windows and Android TV?

on Windows we use MPV and on Android TV we use Media3 / VLC (depending on the user choice)

**Comment by mhdzumair** [comment]
As i tested, currently windows and android tv latest versions are not working with live stream.  So i thought of using docker service as a last option to fix the issue. 

Elfhosted support stremio server to run on the cloud, so as a last option it might be working if the stremio service is support this.

**Comment by jaruba** [comment]
i'm sorry but i don't understand what "live streams" means, you need to specify what types or live streams, it can be HLS, Dash, RTSP, RTMP, you can even stream torrents as live streams.

it should also be noted that each internal video player handles headers differently, the streaming server which serves these live streams may refuse to serve them to Stremio on some platforms because it doesn't like the headers it receives, or the video player may refuse to play them because it doesn't like the headers it gets

this is definitely not a stremio server issue (except for Stremio Web, where technologies such as HLS should be directly supported by the web app)

maybe try using `stream.behaviorHints.proxyHeaders` (which works only when the stremio server is attached) to solution any header requirements for your streams
