### ISSUE TITLE
Allow Enabling HTTPS with ENV Var

### ISSUE THREAD

**Issue by jaruba** [Stremio/server-docker#8]
The server is able to create valid SSL certificates given a LAN IP, but there is no way to set this outside of the Stremio app settings. (when connected to the server)

I propose creating an env var (could be named "REMOTE_HTTPS") that should be set to the LAN IP address in order to provide an SSL certificate for it.

The HTTPS server uses the 12470 port, while the HTTP server uses the 11470. (only 11470 is currently being exposed in this docker image, I believe)

- [x] Expose port 12470
- [ ] Add env. variable for remote https ssl certificate

**Comment by elpiel** [comment]
I've already added the 12470 port to the `Dockerfile`, however, keep in mind that this is for documentation purposes, you still have to expose the port when running the container:

`docker run --rm -d -p 11470:11470 -p 12470:12470 stremio/server:latest`

See PR #13 
https://github.com/Stremio/server-docker/blob/feat/multiplatform-builds/Dockerfile#L57-L58

**Comment by damacchi** [comment]
I get `HTTPS: Request error Could not get a valid HTTPS certificate` in the container logs (on a different computer on the same lan) whenever i hit reload in the webapp streaming settings.

**Comment by vpetkovic** [comment]
Is this issue a reason why I cannot connect to the server unless I expose my container publicly over https (ex: https://stremio.domain.com)? 

Weird thing is when trying to set my server to point to 'http://192.168.1.2:11470' or 'https://192.168.1.2:12470' it fails to connect, but if I copy stream URL ( #19 ) and replace the malformed IP with aforementioned LAN IP video loads and plays,

**Comment by manueljishi** [comment]
> I get `HTTPS: Request error Could not get a valid HTTPS certificate` in the container logs (on a different computer on the same lan) whenever i hit reload in the webapp streaming settings.

@damacchi  I am currently having the same issue, did you manage to fix it?
Thank you very much

**Comment by kennyparsons** [comment]
I think there's an undocumented (or hard to find) endpoint that generates the certs or i think you need to just put self signed certs in the settings directory. PEM file, i think. proto://localhost:11470/get-https

**Comment by tompipe** [comment]
> I think there's an undocumented (or hard to find) endpoint that generates the certs or i think you need to just put self signed certs in the settings directory. PEM file, i think. proto://localhost:11470/get-https

I had to ensure the ipAddress was set in the query string for this to work. e.g

`http://<local docker host ip>:11470/get-https?ipAddress=<local docker host ip>`

This then returned some json, e.g:

```
{
  ipAddress: "<local docker host ip>",
  domain: "<local docker host ip>.519b6502d940.stremio.rocks",
  port: 12470
}
```

And created a httpsCert.json in the data dir with matching details.

The domain it returns has an A record pointing to `<local docker host ip>`. 

Accessing it in a browser redirects to app.strem.io with the correct streamingServer query string passed, and https certs all seem to be working

**Comment by Opinion** [comment]
I believe I found a way to persist the SSL certificate. Here is what I did:

I added `/root/.stremio-server` as a volume;
```
    volumes:
      - ${CONTAINER}/server:/root/.stremio-server
```

Restarted the container and generated the SSL certificate like @tompipe mentioned;
> I had to ensure the ipAddress was set in the query string for this to work. e.g
> 
> `http://<local docker host ip>:11470/get-https?ipAddress=<local docker host ip>`

In my case: `http://192.168.1.69:11470/get-https?ipAddress=192.168.1.69`

---

I also got it working behind a reverse proxy; using nginx-proxy manager with Let's Encrypt certificates.
For this, I recommend owning a domain and adding '*.local' and 'local' as A records pointing to the LAN IP of your server.
 - `A *.local 192.168.1.69`
 - `A local   192.168.1.69`

Here are my proxy host settings:
```
[TAB: Details]
Domain Names:           stremio.local.example.com
Scheme:                 https
Forward Hostname / IP:  192.168.1.69
Forward Port:           12470
Websocket Support:      (checked)

[TAB: SSL]
SSL Certificate:        Request a new SSL Certificate
Force SSL:              (checked)
Use DNS challenge:      (checked)
DNS Provider:           *select your provider and API settings*
```

**Comment by knylbyte** [comment]
> > I think there's an undocumented (or hard to find) endpoint that generates the certs or i think you need to just put self signed certs in the settings directory. PEM file, i think. proto://localhost:11470/get-https
> 
> I had to ensure the ipAddress was set in the query string for this to work. e.g
> 
> `http://<local docker host ip>:11470/get-https?ipAddress=<local docker host ip>`
> 
> This then returned some json, e.g:
> 
> ```
> {
>   ipAddress: "<local docker host ip>",
>   domain: "<local docker host ip>.519b6502d940.stremio.rocks",
>   port: 12470
> }
> ```
> 
> And created a httpsCert.json in the data dir with matching details.
> 
> The domain it returns has an A record pointing to `<local docker host ip>`.
> 
> Accessing it in a browser redirects to app.strem.io with the correct streamingServer query string passed, and https certs all seem to be working

It seems this solution doesn't work anymore. I always get this error message: 
> EngineFS server started at http://127.0.0.1:11470
> EngineFS HTTPS endpoint at https://local.strem.io:12470
> -> GET /get-https?ipAddress=10.0.10.3 
> Cannot get valid certificate TypeError: Cannot read property 'certificate' of undefined
>     at /stremio/server.js:68286:51
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> 

Does anyone else get this message? I'm running the latest image.

Edit: Nevermind, the third attempt worked!
